-- AlterTable
ALTER TABLE "company_settings" ADD COLUMN     "ctaButtonLink" TEXT,
ADD COLUMN     "ctaButtonText" TEXT,
ADD COLUMN     "ctaDescription" TEXT,
ADD COLUMN     "ctaEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "ctaTitle" TEXT,
ADD COLUMN     "heroBackgroundImage" TEXT,
ADD COLUMN     "heroButtonLink" TEXT,
ADD COLUMN     "heroButtonText" TEXT,
ADD COLUMN     "heroSubtitle" TEXT,
ADD COLUMN     "heroTitle" TEXT,
ADD COLUMN     "maxCategoriesDisplay" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN     "showCategories" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showStats" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "stat1Icon" TEXT,
ADD COLUMN     "stat1Label" TEXT,
ADD COLUMN     "stat1Value" TEXT,
ADD COLUMN     "stat2Icon" TEXT,
ADD COLUMN     "stat2Label" TEXT,
ADD COLUMN     "stat2Value" TEXT,
ADD COLUMN     "stat3Icon" TEXT,
ADD COLUMN     "stat3Label" TEXT,
ADD COLUMN     "stat3Value" TEXT,
ADD COLUMN     "stat4Icon" TEXT,
ADD COLUMN     "stat4Label" TEXT,
ADD COLUMN     "stat4Value" TEXT;
